export const tasks = [
  {
    id: "T-STAY-DEPOSIT",
    objectId: "SO-20260528-001",
    domain: "stay",
    title: "depositTask",
    object: "stayObject",
    problem: "depositProblem",
    due: "18:00",
    badges: ["mine", "blocked"],
    priority: 99,
    why: { "zh-CN": "你负责住宿材料补交，财务确认前不能入住。", "ru-RU": "Вы отвечаете за материалы; без финансов заселение недоступно." },
    delay: { "zh-CN": "张三无法入住，A301-02 会停留在锁定状态。", "ru-RU": "Чжан не заселится, койка A301-02 останется заблокированной." },
    next: { "zh-CN": "补交付款截图和收据编号，再等待财务确认。", "ru-RU": "Добавьте чек и номер квитанции, затем ждите финансы." }
  },
  {
    id: "T-AUTO-DIAGNOSE",
    objectId: "AR-20260528-004",
    domain: "repair",
    title: "repairTask",
    object: "repairObject",
    problem: "repairProblem",
    due: "17:30",
    badges: ["mine", "soon"],
    priority: 93,
    why: { "zh-CN": "你负责维修派工，车辆到场后必须先诊断。", "ru-RU": "Вы назначаете ремонт; после прибытия нужна диагностика." },
    delay: { "zh-CN": "车辆继续停运，后续配件和费用无法估算。", "ru-RU": "Авто простаивает, детали и стоимость нельзя оценить." },
    next: { "zh-CN": "选择技师和到场时间，不会自动关闭维修单。", "ru-RU": "Выберите механика и время, заявка не закроется автоматически." }
  },
  {
    id: "T-FIN-DEPOSIT",
    objectId: "FIN-20260528-009",
    domain: "finance",
    title: "financeTask",
    object: "financeObject",
    problem: "financeProblem",
    due: "明天 12:00",
    badges: ["confirm", "waiting"],
    priority: 86,
    why: { "zh-CN": "你是财务确认人，需要人工核对收款证据。", "ru-RU": "Вы финансовый проверяющий, нужна ручная проверка." },
    delay: { "zh-CN": "住宿经办人无法继续办理入住。", "ru-RU": "Оператор проживания не сможет продолжить заселение." },
    next: { "zh-CN": "核对凭证后确认或退回，AI 不可自动通过。", "ru-RU": "Проверьте и подтвердите или верните; AI не проходит автоматически." }
  },
  {
    id: "T-STAY-CHECKOUT",
    objectId: "SO-20260520-003",
    domain: "stay",
    title: "checkout",
    object: "stayObject",
    problem: "办理退房前需要核对房间检查、费用和押金退款材料。",
    due: "今天 19:00",
    badges: ["mine", "soon"],
    priority: 90,
    why: { "zh-CN": "你负责住宿单退房材料，财务结算前需要先完成业务核对。", "ru-RU": "Вы готовите материалы выселения перед фин. расчетом." },
    delay: { "zh-CN": "床位不能释放，押金退款和费用结算都会延迟。", "ru-RU": "Койка не освободится, возврат депозита задержится." },
    next: { "zh-CN": "核对房间检查、费用明细和退款材料后提交确认。", "ru-RU": "Проверьте комнату, расходы и возврат депозита." }
  },
  {
    id: "T-ROOM-CREATE",
    objectId: "ROOM-DRAFT-A302",
    domain: "stay",
    title: "createRoom",
    object: "createRoom",
    problem: "A302 不存在，需先创建房间再创建床位。",
    due: "建档",
    badges: ["mine"],
    priority: 78,
    why: { "zh-CN": "搜索到的房间不存在，后续床位和住宿单都依赖房间档案。", "ru-RU": "Комнаты нет, койки и ордер зависят от карточки комнаты." },
    delay: { "zh-CN": "无法创建床位，也无法为入住申请选择房间。", "ru-RU": "Нельзя создать койку и выбрать комнату для заселения." },
    next: { "zh-CN": "录入楼栋、房间号、房型、容量并校验重复。", "ru-RU": "Введите корпус, номер, тип, вместимость и проверьте дубликаты." }
  },
  {
    id: "T-BED-CREATE",
    objectId: "BED-DRAFT-A302-01",
    domain: "stay",
    title: "createBed",
    object: "createBed",
    problem: "A302 已建房间，但缺少可分配床位。",
    due: "建档",
    badges: ["mine"],
    priority: 76,
    why: { "zh-CN": "床位是住宿单分配的最小对象，必须先建档并通过容量校验。", "ru-RU": "Койка - минимальный объект назначения, нужна проверка вместимости." },
    delay: { "zh-CN": "入住申请无法进入创建住宿单。", "ru-RU": "Заявка не сможет перейти к ордеру." },
    next: { "zh-CN": "选择房间，录入床位号、床位类型、价格和检查状态。", "ru-RU": "Выберите комнату, номер койки, тип, цену и статус проверки." }
  },
  {
    id: "T-VEHICLE-CREATE",
    objectId: "VEH-DRAFT-01KG999",
    domain: "repair",
    title: "createVehicle",
    object: "createVehicle",
    problem: "车牌 01KG999XYZ 未建档，不能创建维修单。",
    due: "建档",
    badges: ["mine"],
    priority: 80,
    why: { "zh-CN": "维修单必须绑定客户和车辆资料，避免后续费用、历史和验收找不到对象。", "ru-RU": "Ремонт должен быть связан с клиентом и авто." },
    delay: { "zh-CN": "无法报修、派工或沉淀维修历史。", "ru-RU": "Нельзя создать ремонт и историю обслуживания." },
    next: { "zh-CN": "选择客户，录入车牌、品牌车型、VIN、发动机号和里程。", "ru-RU": "Выберите клиента, введите номер, модель, VIN, двигатель и пробег." }
  },
  {
    id: "T-REPAIR-CLOSE",
    objectId: "AR-20260527-002",
    domain: "repair",
    title: "repairInspect",
    object: "repairObject",
    problem: "维修已完成，等待验收、费用材料和关闭确认。",
    due: "明天 10:00",
    badges: ["confirm", "waiting"],
    priority: 84,
    why: { "zh-CN": "你是验收确认人，关闭维修单前必须确认结果和费用材料。", "ru-RU": "Вы подтверждаете приемку перед закрытием." },
    delay: { "zh-CN": "车辆不能恢复可用，费用材料无法进入财务。", "ru-RU": "Авто не станет доступным, расходы не уйдут в финансы." },
    next: { "zh-CN": "核对维修照片、验收结论、材料费用后人工关闭。", "ru-RU": "Проверьте фото, приемку, материалы и закройте вручную." }
  }
];
