namespace WorkOS.Api.Runtime;

internal static class EvidenceContractCatalog
{
    public static IReadOnlyList<EvidenceRequirement> ForCard(string cardId) =>
        Labels(cardId).Select(label => new EvidenceRequirement(
            ContractText.FieldId(label),
            ContractText.Text(label, ContractText.TermRu(label)),
            true,
            label.Contains("照片") || label.Contains("截图") || label.Contains("凭证") ? "upload" : "record",
            ContractText.FieldId(label),
            ContractText.Text("提交前需要核对这项证据，确认后会进入审计事件。", "Проверьте это доказательство перед отправкой; после подтверждения оно попадет в аудит."))).ToArray();

    private static string[] Labels(string cardId) => cardId switch
    {
        "lead" => new[] { "联系方式记录", "来源渠道记录" },
        "booking" => new[] { "预订确认记录", "床位预留记录" },
        "resident" => new[] { "入住人身份记录", "联系电话记录" },
        "bedAssign" => new[] { "床位可用校验", "床位锁定记录" },
        "tariff" => new[] { "计费规则记录", "应收生成记录" },
        "depositRequirement" => new[] { "押金规则记录", "押金责任账本记录" },
        "payment" => new[] { "付款截图", "收据编号", "收款人记录" },
        "operatingDashboard" => new[] { "经营指标快照", "后续行动记录" },
        "application" => new[] { "已审批申请", "审批意见" },
        "stayOrder" => new[] { "已审批申请", "房间床位" },
        "deposit" => new[] { "付款截图", "收据编号", "付款人", "付款时间" },
        "finance" => new[] { "到账记录", "金额核对", "财务确认记录" },
        "checkin" => new[] { "钥匙/物品交接", "入住人现场确认" },
        "roomSetup" => new[] { "房间重复校验", "配置人记录" },
        "bedSetup" => new[] { "床位容量校验", "床位编号校验" },
        "rateSetup" => new[] { "价格规则记录", "生效日期记录" },
        "roomReadiness" => new[] { "准备度核对记录", "房态更新记录" },
        "roomBlock" => new[] { "阻断原因记录", "阻断时间记录" },
        "roomRelease" => new[] { "释放确认记录", "房态恢复记录" },
        "leadCapture" => new[] { "联系方式记录", "来源渠道记录" },
        "leadFollowUp" => new[] { "跟进记录", "线索状态记录" },
        "reservationCreate" => new[] { "预订确认记录", "床位预留记录" },
        "reservationCancel" => new[] { "取消原因记录", "床位释放记录" },
        "reservationConvert" => new[] { "预订转入住记录", "住客承诺记录" },
        "residentProfile" => new[] { "住客身份记录", "联系电话记录" },
        "checkInBedAssign" => new[] { "床位可用校验", "入住周期记录" },
        "chargeAssessment" => new[] { "应收生成记录", "计费原因记录" },
        "stayExtension" => new[] { "续住原因记录", "新增应收记录" },
        "depositAssessment" => new[] { "押金规则记录", "押金责任账本记录" },
        "depositReceipt" => new[] { "押金凭证", "押金收款记录" },
        "depositConfirmation" => new[] { "到账记录", "财务确认记录" },
        "depositDeduction" => new[] { "扣除原因记录", "押金余额记录" },
        "depositRefundApproval" => new[] { "退款审批记录", "扣除抵欠记录" },
        "depositRefundPayment" => new[] { "退款凭证", "退款接收人记录" },
        "depositClose" => new[] { "押金关闭记录", "负债余额记录" },
        "paymentReceipt" => new[] { "收款凭证", "收款人记录" },
        "paymentConfirmation" => new[] { "到账记录", "财务确认记录" },
        "paymentAllocation" => new[] { "应收分配记录", "余额重算记录" },
        "paymentAdjustment" => new[] { "调整原因记录", "余额重算记录" },
        "debtFollowUp" => new[] { "欠款跟进记录", "下一步责任记录" },
        "depositSettlement" => new[] { "押金结算记录", "扣除抵欠记录" },
        "finalBalanceClose" => new[] { "余额关闭记录", "结算结果记录" },
        "bedRelease" => new[] { "床位释放记录", "退住关闭记录" },
        "postCheckoutCleaning" => new[] { "清洁任务记录", "房态阻断记录" },
        "serviceTaskCreate" => new[] { "任务凭证", "阻断可售记录" },
        "serviceTaskAssign" => new[] { "分派记录", "责任人记录" },
        "serviceTaskComplete" => new[] { "完成凭证", "成本记录" },
        "serviceTaskVerify" => new[] { "验收记录", "返工记录" },
        "roomReleaseAfterService" => new[] { "释放确认记录", "房态恢复记录" },
        "expenseRecord" => new[] { "支出凭证", "付款记录" },
        "expenseApproval" => new[] { "审批记录", "确认金额记录" },
        "expenseLink" => new[] { "支出关联记录", "成本归集记录" },
        "periodScope" => new[] { "周期范围记录", "复盘说明记录" },
        "periodMetricsReview" => new[] { "指标快照", "指标复核记录" },
        "periodFinanceReview" => new[] { "财务快照", "财务复核记录" },
        "periodOperationsDiagnosis" => new[] { "运营诊断记录", "根因分析记录" },
        "periodActionPlan" => new[] { "行动计划记录", "负责人记录" },
        "periodClose" => new[] { "周期关闭记录", "管理结论记录" },
        _ => new[] { "操作证据", "人工处理记录" }
    };
}
