namespace WorkOS.Api.Runtime;

internal static class SystemCheckCatalog
{
    public static IReadOnlyList<SystemCheck> ForCard(string cardId) =>
        Labels(cardId).Select(label => new SystemCheck(ContractText.FieldId(label), ContractText.Text(label, label), "blocking", "pending")).ToArray();

    private static string[] Labels(string cardId) => cardId switch
    {
        "lead" => new[] { "联系方式完整", "线索未重复" },
        "booking" => new[] { "床位可预留", "入住日期有效" },
        "resident" => new[] { "住客未重复在住", "计划退住日期有效" },
        "bedAssign" => new[] { "床位可用", "入住周期无冲突", "房间未维修阻断" },
        "tariff" => new[] { "计费方式有效", "应收金额可计算", "Folio 可生成" },
        "depositRequirement" => new[] { "押金规则有效", "责任账本可入账", "免押原因已记录" },
        "payment" => new[] { "收款用途有效", "凭证编号未重复", "支付待财务确认" },
        "operatingDashboard" => new[] { "入住率已更新", "押金责任已更新", "未确认金额已更新", "转化率已更新" },
        "application" => new[] { "申请已审批", "入住人未重复入住" },
        "stayOrder" => new[] { "床位可用", "入住周期无冲突", "押金/费用规则可用" },
        "deposit" => new[] { "金额匹配", "币种匹配", "付款人匹配", "凭证清晰" },
        "finance" => new[] { "到账状态有效", "确认金额一致", "财务角色可确认" },
        "checkin" => new[] { "押金已通过", "床位仍锁定", "人工确认完整" },
        "roomSetup" => new[] { "房间号未重复", "床位数有效", "房间配置完整" },
        "bedSetup" => new[] { "房间存在", "未超过床位数", "床位号未重复" },
        "rateSetup" => new[] { "房间存在", "价格币种有效", "生效日期有效" },
        "roomReadiness" => new[] { "房间存在", "家具技术状态已核对", "可售状态可解释" },
        "roomBlock" => new[] { "房间床位存在", "阻断范围有效", "预计恢复时间有效" },
        "roomRelease" => new[] { "阻断记录存在", "释放范围有效", "恢复可售时间有效" },
        "leadCapture" => new[] { "联系方式完整", "线索未重复" },
        "leadFollowUp" => new[] { "跟进时间有效", "线索状态可变更" },
        "reservationCreate" => new[] { "床位可预留", "保留截止时间有效" },
        "reservationCancel" => new[] { "预订可取消", "床位可释放" },
        "reservationConvert" => new[] { "预订可转入住", "入住资料未重复" },
        "residentProfile" => new[] { "住客未重复在住", "联系电话完整" },
        "checkInBedAssign" => new[] { "床位可用", "房间未维修阻断", "入住周期无冲突" },
        "chargeAssessment" => new[] { "应收金额可计算", "入住单存在" },
        "stayExtension" => new[] { "续住周期有效", "新增应收可生成" },
        "depositAssessment" => new[] { "押金规则有效", "押金不计收入" },
        "depositReceipt" => new[] { "非现金押金凭证完整", "押金待财务确认" },
        "depositConfirmation" => new[] { "财务角色可确认", "押金到账金额有效" },
        "depositDeduction" => new[] { "押金扣除不超过持有金额", "扣除原因完整" },
        "depositRefundApproval" => new[] { "退款扣除抵欠不超过持有押金", "押金退款不计支出" },
        "depositRefundPayment" => new[] { "押金退款已审批", "退款凭证完整", "押金退款不计支出" },
        "depositClose" => new[] { "押金余额已结清", "关闭结果完整" },
        "paymentReceipt" => new[] { "非现金收款凭证完整", "普通收款不含押金" },
        "paymentConfirmation" => new[] { "财务角色可确认", "确认金额有效" },
        "paymentAllocation" => new[] { "分配金额不超过确认金额", "应收项存在" },
        "paymentAdjustment" => new[] { "调整原因完整", "余额可重算" },
        "debtFollowUp" => new[] { "欠款余额存在", "跟进记录完整" },
        "depositSettlement" => new[] { "押金结算不超过持有金额", "押金不计收入" },
        "finalBalanceClose" => new[] { "余额已复核", "押金退款不计支出" },
        "bedRelease" => new[] { "退住已开始", "床位可释放" },
        "postCheckoutCleaning" => new[] { "清洁任务可生成", "房态阻断已记录" },
        "serviceTaskCreate" => new[] { "服务对象存在", "阻断可售状态可更新" },
        "serviceTaskAssign" => new[] { "任务可分派", "责任人已记录" },
        "serviceTaskComplete" => new[] { "任务可完成", "完成凭证完整" },
        "serviceTaskVerify" => new[] { "任务可验收", "验收结果完整" },
        "roomReleaseAfterService" => new[] { "服务任务已验收", "房间床位可请求恢复可售" },
        "expenseRecord" => new[] { "支出凭证完整", "支出不含押金退款" },
        "expenseApproval" => new[] { "审批角色可确认", "确认金额有效" },
        "expenseLink" => new[] { "关联对象存在", "成本归集有效" },
        "periodScope" => new[] { "周期范围有效", "周期未重复" },
        "periodMetricsReview" => new[] { "指标快照存在", "入住率可解释" },
        "periodFinanceReview" => new[] { "押金不计收入", "押金退款不计支出", "财务异常已识别" },
        "periodOperationsDiagnosis" => new[] { "运营指标存在", "主要问题已分类" },
        "periodActionPlan" => new[] { "行动计划有负责人", "截止日期有效" },
        "periodActionPlanComplete" => new[] { "行动计划存在", "完成结果完整" },
        "periodClose" => new[] { "范围已确认", "指标已复核", "财务已复核", "运营已诊断", "无阻断不变量", "业务签署完成", "高风险有行动计划" },
        _ => new[] { "字段完整", "证据完整", "权限满足" }
    };
}
